# User-Defined Models

The **subdiff** tools can be applied to a large family of user-defined models.   These are based on the location-scale modeling framework of @lysy.etal16, whereby the particle trajectory $\XX(t)$ is given by
\begin{equation}
  \XX(t) = \RR(t \mid \pph)' \mmu + \SSi^{1/2} \ZZ(t),
  (\#eq:locscale)
\end{equation}
where:

- $\ZZ(t) = \big(Z_1(t), \ldots, Z_{\ndim}(t)\big)$ are independent and identically distributed (iid) copies of a CSI process $Z(t)$ having MSD

	$$
	\msd_Z(t) = \eta(t \mid \pph).
	$$

- $\SSi$ is a $\ndim \times \ndim$ symmetric positive-definite scaling matrix.

- $\RR(t \mid \pph) = \big( R_1(t \mid \pph), \ldots, R_{\ndrift}(t \mid \pph) \big)$ is a set of $\ndrift$ drift basis functions.  Typically it will be linear or quadratic, corresponding to $\RR(t) = t$ and $\RR(t) = (t, t^2)$ with $\ndrift = 1$ and $\ndrift = 2$, respectively.  However, **subdiff** allows for an arbitrary number of basis functions possibly dependent on the "kernel" parameters $\pph$.

- $\mmu$ is $\ndrift \times \ndim$ matrix of drift coefficients.  For linear drift, $\mmu = (\rv \mu \ndim)$ correspond to per-coordinate drift velocities.

An attractive feature of model \@ref(eq:locscale) is that the MSD of the drift-subtracted particle trajectory $\tilde{\XX}(t) = \XX(t) - \RR(t)' \mmu$ has the simple formula

$$
\msd_{\tilde{\XX}} = \tfrac 1 {\ndim} \tr(\SSi) \cdot  \eta(t \mid \pph).
$$

Another appealing property of this model is that its parameters $\tth = (\pph, \mmu, \SSi)$ can be estimated from discrete observations $\XX = (\rv [0] {\XX} N)$ in a computationally efficient manner [@ling.etal20].

## Example: Brownian Motion in a Jeffreys Fluid

Consider a particle of radius $r$ in a Jeffreys fluid described by viscosity parameters $\eta_1$ and $\eta_2$ and elastic modulus $\Gamma$.  The MSD of the drift-subtracted particle trajectory $\tilde{\XX}(t)$ is given by [@raikher.rusakov10]

\begin{equation}
\msd_{\tilde{\XX}}(t) = \frac{2 \kbt}{\xi_V(1+q)} \times \left\{t + \frac{q}{1+q} \tau_M \left[1 - \exp\left(-\frac{(1+q)t}{\tau_M}\right)\right]\right\},
(\#eq:jfsmsd)
\end{equation}

where $q = \eta_1/\eta_2$, $\tau_M = (\eta_1 + \eta_2)/\Gamma$, and $\xi_V = 6\pi r \cdot \eta_1\eta_2/(\eta_1 + \eta_2)$.  A more natural parametrization is

$$
\msd_{\tilde{\XX}}(t) = \sigma^2 \left\{t + \alpha \left[1 - e^{-t/\tau}\right]\right\},
$$

where $\tau = \tau_M/(1+q) = \eta_2/\Gamma$, $\alpha = \tau q = \eta_1/\Gamma$, and $\sigma^2 = 2\kbt / (\xi_V(1+q)) = 2\kbt / (6\pi r \eta_1)$.  In the formulation of the location-scale model \@ref(eq:locscale), the CSI process $Z(t)$ underlying the particle trajectory $\XX(t)$ has MSD

$$
\eta(t \mid \pph) = \msd_Z(t) = \left\{t + \alpha \left[1 - e^{-t/\tau}\right]\right\}
$$

with $\pph = (\alpha, \tau)$, and the MSD scale factor is $\sigma^2 = \tr(\SSi)/\ndim$.

In order to fit the Jeffreys model \@ref(eq:jfsmsd) to trajectory data, we will create a class `jfs_model` which will derive from the base class `csi_model` used to represent the general location-scale model \@ref(eq:locscale).  In order to do this, we will need the following ingredients:


