# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ModePoly <- function(roots, nIter, tol) {
    .Call(`_subdiff_ModePoly`, roots, nIter, tol)
}

.SampleMSD <- function(X, nLags) {
    .Call(`_subdiff_SampleMSD`, X, nLags)
}

log1pe <- function(x) {
    .Call(`_subdiff_log1pexp_wrapper`, x)
}

ma1_resid <- function(Xt, rho) {
    .Call(`_subdiff_ma1Resid`, Xt, rho)
}

ma2_resid <- function(Xt, rho1, rho2) {
    .Call(`_subdiff_ma2Resid`, Xt, rho1, rho2)
}

ma3_resid <- function(Xt, rho1, rho2, rho3) {
    .Call(`_subdiff_ma3Resid`, Xt, rho1, rho2, rho3)
}

