# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log1pe <- function(x) {
    .Call(`_subdiff_log1pe`, x)
}

ls_var <- function(alpha, lags, N) {
    .Call(`_subdiff_ls_var`, alpha, lags, N)
}

mode_poly <- function(roots, n_iter, tol) {
    .Call(`_subdiff_mode_poly`, roots, n_iter, tol)
}

msd_empirical <- function(Xt, n_lag) {
    .Call(`_subdiff_msd_empirical`, Xt, n_lag)
}

